### ISSUE TITLE
PSNR on LOL dataset shown in the Tabel. 2

### ISSUE THREAD

**Issue by yarqian** [hitzhangyu/image-enhancement-with-denoise#2]
I am quite confused about the PSNR result on the LOL dataset shown in the Table.2. It seems that the original ones are much higher than that claimed in their papers. For example, a shown in the Table. 2, the gamma correction can achieved 21.95db on the LOL dataset. I don't think the gamma correction can achieve such performance. 
Many thanks.

**Comment by hitzhangyu** [comment]
It is on the sixth page of the manuscript：
**“Please note that SSIM and PSNR are mainly used to evaluate structure and noise, but brightness differences will have a serious impact on the evaluation of these metrics. In order to better evaluate the results generated by different methods, we first perform a local brightness mapping on the enhanced image to exclude the influence of brightness differences before using SSIM and PSNR, which is the same as in Equation (16).”**

**Comment by yarqian** [comment]
I see. But the parameter w in Eq. (16) is calculated with the reference image **Y**.

**Comment by hitzhangyu** [comment]
Yes, but this mapping operation does not affect the noise or structure of the enhanced image, it only changes the local brightness information. And PSNR and SSIM are all calculated with the reference image Y originally.

.

**Comment by yarqian** [comment]
Many thanks for your reply and I will close this issue.
